FROM <%= options.image %>
  
WORKDIR /app

COPY  <%= options.inputPath %>          /app/service

<%=
  assets.map((i) => `RUN   mkdir -p ${i[1]} \nCOPY  ${i[0]}          ${i[1]}`).join('\n')
%>

EXPOSE <%= options.exposePort %>
  
CMD [ "/app/service" ]
